# 站点名称
title: 主题演示
# 站点描述
description: vuepress-theme-hope 的演示
# 输出目录
dest: ./dist
# 设置根目录语言
locales:
  /:
    lang: zh-CN
# 使用本主题
theme: hope
# 主题配置
themeConfig:
  # 导航栏图标
  logo: /logo.svg
  # 请设置为你的部署站点
  hostname: https://mister-hope.github.io
  # 请改成你的名字
  author: Mr.Hope
